# Generated by Django 5.1.4 on 2025-01-24 11:30

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_options_alter_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
